# This is a basic workflow to help you get started with Actions

name: Pull Request Quality Checks

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
      - feat/*
  workflow_dispatch:

jobs:
  build:
    name: PR checks
    runs-on: ubuntu-latest
    env:
      UV_VERSION: "0.5.11"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          make build
          make install-dev

      - name: Run Quality Checks
        run: make qa